### ISSUE TITLE
Error resolving classname on requiring dali and dependencies from Babashka

### ISSUE THREAD

**Issue by marrs** [stathissideris/dali#28]
This is a Babashka issue.  The library installs fine via `deps.edn`.

I have a `bb.edn` with the following content

```
{:paths ["bb"]
 :deps { dali/dali {:mvn/version "1.0.2"}}}
```

And a script I am attempting to run:

```
#!/usr/bin/env bb

(require '[dali.io :as io])
```

Installation of the dali dependencies fails with the following error:

`Unable to resolve classname: org.xml.sax.ContentHandler`

The entire output is below:

```
Downloading: dali/dali/1.0.2/dali-1.0.2.pom from clojars
Downloading: org/clojure/data.codec/0.1.0/data.codec-0.1.0.pom from central
Downloading: org/apache/xmlgraphics/batik-transcoder/1.8/batik-transcoder-1.8.pom from central
Downloading: org/apache/xmlgraphics/batik-anim/1.8/batik-anim-1.8.pom from central
Downloading: org/clojure/pom.contrib/0.0.25/pom.contrib-0.0.25.pom from central
Downloading: org/apache/xmlgraphics/batik-codec/1.8/batik-codec-1.8.pom from central
Downloading: org/apache/xmlgraphics/xmlgraphics-commons/2.0.1/xmlgraphics-commons-2.0.1.pom from central
Downloading: xerces/xerces/2.4.0/xerces-2.4.0.pom from central
Downloading: org/apache/apache/7/apache-7.pom from central
Downloading: xerces/xercesImpl/2.4.0/xercesImpl-2.4.0.pom from central
Downloading: enlive/enlive/1.1.6/enlive-1.1.6.pom from clojars
Downloading: retrograde/retrograde/0.10/retrograde-0.10.pom from clojars
Downloading: prismatic/schema/1.0.3/schema-1.0.3.pom from clojars
Downloading: org/apache/xmlgraphics/batik-xml/1.8/batik-xml-1.8.pom from central
Downloading: org/apache/xmlgraphics/batik-svggen/1.8/batik-svggen-1.8.pom from central
Downloading: org/apache/xmlgraphics/batik-util/1.8/batik-util-1.8.pom from central
Downloading: xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.pom from central
Downloading: xml-apis/xml-apis-ext/1.3.04/xml-apis-ext-1.3.04.pom from central
Downloading: org/apache/xmlgraphics/batik-gvt/1.8/batik-gvt-1.8.pom from central
Downloading: org/apache/xmlgraphics/batik-css/1.8/batik-css-1.8.pom from central
Downloading: org/apache/xmlgraphics/batik-bridge/1.8/batik-bridge-1.8.pom from central
Downloading: org/ccil/cowan/tagsoup/tagsoup/1.2.1/tagsoup-1.2.1.pom from central
Downloading: org/jsoup/jsoup/1.7.2/jsoup-1.7.2.pom from central
Downloading: org/apache/xmlgraphics/batik-awt-util/1.8/batik-awt-util-1.8.pom from central
Downloading: org/apache/xmlgraphics/batik-dom/1.8/batik-dom-1.8.pom from central
Downloading: org/apache/apache/3/apache-3.pom from central
Downloading: org/apache/xmlgraphics/batik-ext/1.8/batik-ext-1.8.pom from central
Downloading: org/apache/xmlgraphics/batik-svg-dom/1.8/batik-svg-dom-1.8.pom from central
Downloading: org/apache/xmlgraphics/batik-parser/1.8/batik-parser-1.8.pom from central
Downloading: commons-io/commons-io/1.3.1/commons-io-1.3.1.pom from central
Downloading: commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.pom from central
Downloading: org/apache/xmlgraphics/batik-script/1.8/batik-script-1.8.pom from central
Downloading: xalan/xalan/2.7.0/xalan-2.7.0.pom from central
Downloading: xml-apis/xml-apis/2.0.2/xml-apis-2.0.2.pom from central
Downloading: xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.pom from central
Downloading: org/ccil/cowan/tagsoup/tagsoup/1.2.1/tagsoup-1.2.1.jar from central
Downloading: xml-apis/xml-apis-ext/1.3.04/xml-apis-ext-1.3.04.jar from central
Downloading: org/apache/xmlgraphics/batik-gvt/1.8/batik-gvt-1.8.jar from central
Downloading: xalan/xalan/2.7.0/xalan-2.7.0.jar from central
Downloading: org/apache/xmlgraphics/batik-svggen/1.8/batik-svggen-1.8.jar from central
Downloading: org/apache/xmlgraphics/batik-parser/1.8/batik-parser-1.8.jar from central
Downloading: commons-io/commons-io/1.3.1/commons-io-1.3.1.jar from central
Downloading: org/apache/xmlgraphics/batik-bridge/1.8/batik-bridge-1.8.jar from central
Downloading: org/apache/xmlgraphics/batik-css/1.8/batik-css-1.8.jar from central
Downloading: org/apache/xmlgraphics/batik-dom/1.8/batik-dom-1.8.jar from central
Downloading: org/apache/xmlgraphics/batik-transcoder/1.8/batik-transcoder-1.8.jar from central
Downloading: org/apache/xmlgraphics/batik-svg-dom/1.8/batik-svg-dom-1.8.jar from central
Downloading: org/apache/xmlgraphics/batik-xml/1.8/batik-xml-1.8.jar from central
Downloading: org/apache/xmlgraphics/xmlgraphics-commons/2.0.1/xmlgraphics-commons-2.0.1.jar from central
Downloading: xerces/xerces/2.4.0/xerces-2.4.0.jar from central
Downloading: org/apache/xmlgraphics/batik-script/1.8/batik-script-1.8.jar from central
Downloading: org/apache/xmlgraphics/batik-anim/1.8/batik-anim-1.8.jar from central
Downloading: commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar from central
Downloading: xml-apis/xml-apis/2.0.2/xml-apis-2.0.2.jar from central
Downloading: org/apache/xmlgraphics/batik-awt-util/1.8/batik-awt-util-1.8.jar from central
Downloading: org/apache/xmlgraphics/batik-util/1.8/batik-util-1.8.jar from central
Downloading: org/apache/xmlgraphics/batik-codec/1.8/batik-codec-1.8.jar from central
Downloading: org/jsoup/jsoup/1.7.2/jsoup-1.7.2.jar from central
Downloading: org/apache/xmlgraphics/batik-ext/1.8/batik-ext-1.8.jar from central
Downloading: org/clojure/data.codec/0.1.0/data.codec-0.1.0.jar from central
Downloading: retrograde/retrograde/0.10/retrograde-0.10.jar from clojars
Downloading: enlive/enlive/1.1.6/enlive-1.1.6.jar from clojars
Downloading: dali/dali/1.0.2/dali-1.0.2.jar from clojars
Downloading: prismatic/schema/1.0.3/schema-1.0.3.jar from clojars
----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  Unable to resolve classname: org.xml.sax.ContentHandler
Location: net/cgrand/xml.clj:11:3

----- Context ------------------------------------------------------------------
 7: ;   You must not remove this notice, or any other, from this software.
 8:
 9: (ns net.cgrand.xml
10:   (:require [clojure.zip :as z])
11:   (:import (org.xml.sax ContentHandler Attributes SAXException XMLReader)
      ^--- Unable to resolve classname: org.xml.sax.ContentHandler
12:            (org.xml.sax.ext DefaultHandler2)
13:            (javax.xml.parsers SAXParser SAXParserFactory)))
14:
15: (defstruct element :tag :attrs :content)
16:

----- Stack trace --------------------------------------------------------------
net.cgrand.xml         - net/cgrand/xml.clj:11:3
net.cgrand.tagsoup     - net/cgrand/tagsoup.clj:12:3
net.cgrand.enlive-html - net/cgrand/enlive_html.clj:14:3
dali.syntax            - dali/syntax.clj:2:3
dali.dom               - dali/dom.clj:2:3
dali.batik             - dali/batik.clj:2:3
dali.io                - dali/io.clj:3:3
```
